# Generated by Django 5.1.4 on 2026-08-28 03:23

import apps.after_sales.models
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cart_orders', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentConversation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('state', models.CharField(choices=[('ACTIVE', '处理中'), ('AWAITING_DETAILS', '等待补充信息'), ('AWAITING_CONFIRMATION', '等待用户确认'), ('ESCALATED', '已转人工'), ('RESOLVED', '已解决'), ('FAILED', '处理失败')], default='ACTIVE', max_length=32, verbose_name='会话状态')),
                ('current_intent', models.CharField(blank=True, max_length=64, verbose_name='当前意图')),
                ('summary', models.TextField(blank=True, verbose_name='会话摘要')),
                ('tool_failure_count', models.PositiveSmallIntegerField(default=0, verbose_name='连续工具失败次数')),
                ('context', models.JSONField(blank=True, default=dict, verbose_name='会话上下文')),
                ('last_active_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='最后活跃时间')),
                ('selected_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agent_conversations', to='cart_orders.order', verbose_name='当前订单')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agent_conversations', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': 'Agent 会话',
                'verbose_name_plural': 'Agent 会话',
                'ordering': ('-last_active_at',),
            },
        ),
        migrations.CreateModel(
            name='AgentMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('role', models.CharField(choices=[('USER', '用户'), ('ASSISTANT', '助手'), ('TOOL', '工具'), ('SYSTEM', '系统')], max_length=16, verbose_name='角色')),
                ('content', models.TextField(blank=True, verbose_name='消息内容')),
                ('tool_name', models.CharField(blank=True, max_length=100, verbose_name='工具名称')),
                ('tool_call_id', models.UUIDField(blank=True, null=True, verbose_name='工具调用标识')),
                ('tool_arguments', models.JSONField(blank=True, default=dict, verbose_name='脱敏工具参数')),
                ('tool_result', models.JSONField(blank=True, default=dict, verbose_name='工具结果')),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='after_sales.agentconversation', verbose_name='会话')),
            ],
            options={
                'verbose_name': 'Agent 消息',
                'verbose_name_plural': 'Agent 消息',
                'ordering': ('created_at',),
            },
        ),
        migrations.CreateModel(
            name='ConfirmationRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('action_type', models.CharField(choices=[('REFUND_REQUEST', '提交退款申请'), ('RETURN_REFUND_REQUEST', '提交退货退款申请'), ('CANCEL_ORDER', '取消待支付订单'), ('HUMAN_TICKET', '提交人工服务工单')], max_length=32, verbose_name='操作类型')),
                ('status', models.CharField(choices=[('PENDING', '待确认'), ('CONFIRMED', '已确认'), ('REJECTED', '已拒绝'), ('EXPIRED', '已过期'), ('EXECUTED', '已执行'), ('FAILED', '执行失败')], default='PENDING', max_length=16, verbose_name='确认状态')),
                ('payload', models.JSONField(default=dict, verbose_name='待执行参数')),
                ('result', models.JSONField(blank=True, default=dict, verbose_name='执行结果')),
                ('idempotency_key', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='幂等键')),
                ('expires_at', models.DateTimeField(verbose_name='过期时间')),
                ('confirmed_at', models.DateTimeField(blank=True, null=True, verbose_name='确认时间')),
                ('executed_at', models.DateTimeField(blank=True, null=True, verbose_name='执行时间')),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='confirmation_requests', to='after_sales.agentconversation', verbose_name='会话')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='confirmation_requests', to='cart_orders.order', verbose_name='订单')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='confirmation_requests', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '确认请求',
                'verbose_name_plural': '确认请求',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='AfterSalesCase',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('case_number', models.CharField(default=apps.after_sales.models.generate_case_number, editable=False, max_length=20, unique=True, verbose_name='工单编号')),
                ('case_type', models.CharField(choices=[('REFUND', '退款申请'), ('RETURN_REFUND', '退货退款申请'), ('QUALITY_ISSUE', '质量问题'), ('DELIVERY_ISSUE', '物流异常'), ('ORDER_VERIFICATION', '订单核验'), ('HUMAN_SERVICE', '人工服务'), ('SYSTEM_EXCEPTION', '系统异常')], max_length=32, verbose_name='工单类型')),
                ('status', models.CharField(choices=[('PENDING_REVIEW', '待人工审核'), ('IN_REVIEW', '审核中'), ('NEED_CUSTOMER_INFO', '待用户补充'), ('APPROVED', '已通过'), ('REJECTED', '已拒绝'), ('CLOSED', '已关闭'), ('CANCELLED', '用户取消')], default='PENDING_REVIEW', max_length=24, verbose_name='工单状态')),
                ('priority', models.CharField(choices=[('LOW', '低'), ('NORMAL', '普通'), ('HIGH', '高'), ('URGENT', '紧急')], default='NORMAL', max_length=16, verbose_name='优先级')),
                ('reason', models.TextField(verbose_name='用户原因')),
                ('agent_summary', models.TextField(blank=True, verbose_name='Agent 摘要')),
                ('staff_note', models.TextField(blank=True, verbose_name='客服备注')),
                ('resolved_at', models.DateTimeField(blank=True, null=True, verbose_name='处理完成时间')),
                ('assigned_to', models.ForeignKey(blank=True, limit_choices_to={'is_staff': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_after_sales_cases', to=settings.AUTH_USER_MODEL, verbose_name='处理人')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='after_sales_cases', to='cart_orders.order', verbose_name='关联订单')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='after_sales_cases', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
                ('conversation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='after_sales_cases', to='after_sales.agentconversation', verbose_name='来源会话')),
                ('confirmation_request', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='after_sales_case', to='after_sales.confirmationrequest', verbose_name='确认请求')),
            ],
            options={
                'verbose_name': '售后工单',
                'verbose_name_plural': '售后工单',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='CustomerMemory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('memory_type', models.CharField(choices=[('PREFERENCE', '偏好'), ('CASE_SUMMARY', '售后摘要'), ('CONVERSATION_SUMMARY', '会话摘要')], max_length=32, verbose_name='记忆类型')),
                ('key', models.CharField(max_length=100, verbose_name='记忆键')),
                ('value', models.JSONField(default=dict, verbose_name='记忆内容')),
                ('is_active', models.BooleanField(default=True, verbose_name='启用')),
                ('source_conversation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='memories', to='after_sales.agentconversation', verbose_name='来源会话')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_memories', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '用户记忆',
                'verbose_name_plural': '用户记忆',
                'ordering': ('-updated_at',),
            },
        ),
        migrations.CreateModel(
            name='ToolExecution',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tool_name', models.CharField(max_length=100, verbose_name='工具名称')),
                ('action_kind', models.CharField(choices=[('READ', '只读'), ('WRITE', '写操作')], max_length=8, verbose_name='操作类型')),
                ('status', models.CharField(choices=[('PENDING', '执行中'), ('SUCCEEDED', '成功'), ('FAILED', '失败'), ('DENIED', '已拒绝')], default='PENDING', max_length=16, verbose_name='执行状态')),
                ('initiated_by', models.CharField(choices=[('AGENT', 'Agent'), ('SYSTEM', '系统'), ('HUMAN', '人工')], default='AGENT', max_length=16, verbose_name='发起方')),
                ('sanitized_arguments', models.JSONField(blank=True, default=dict, verbose_name='脱敏参数')),
                ('result', models.JSONField(blank=True, default=dict, verbose_name='执行结果')),
                ('error_code', models.CharField(blank=True, max_length=100, verbose_name='错误代码')),
                ('duration_ms', models.PositiveIntegerField(blank=True, null=True, verbose_name='耗时（毫秒）')),
                ('after_sales_case', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tool_executions', to='after_sales.aftersalescase', verbose_name='售后工单')),
                ('confirmation_request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tool_executions', to='after_sales.confirmationrequest', verbose_name='确认请求')),
                ('conversation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tool_executions', to='after_sales.agentconversation', verbose_name='会话')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tool_executions', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '工具执行审计',
                'verbose_name_plural': '工具执行审计',
                'ordering': ('-created_at',),
            },
        ),
        migrations.AddIndex(
            model_name='agentconversation',
            index=models.Index(fields=['user', 'state'], name='after_sales_user_id_47fa37_idx'),
        ),
        migrations.AddIndex(
            model_name='agentconversation',
            index=models.Index(fields=['state', 'last_active_at'], name='after_sales_state_38a91e_idx'),
        ),
        migrations.AddIndex(
            model_name='agentmessage',
            index=models.Index(fields=['conversation', 'created_at'], name='after_sales_convers_4abb0a_idx'),
        ),
        migrations.AddIndex(
            model_name='confirmationrequest',
            index=models.Index(fields=['user', 'status'], name='after_sales_user_id_bbbe8e_idx'),
        ),
        migrations.AddIndex(
            model_name='confirmationrequest',
            index=models.Index(fields=['status', 'expires_at'], name='after_sales_status_04529b_idx'),
        ),
        migrations.AddIndex(
            model_name='aftersalescase',
            index=models.Index(fields=['user', 'status'], name='after_sales_user_id_575233_idx'),
        ),
        migrations.AddIndex(
            model_name='aftersalescase',
            index=models.Index(fields=['status', 'priority'], name='after_sales_status_327587_idx'),
        ),
        migrations.AddIndex(
            model_name='aftersalescase',
            index=models.Index(fields=['order', 'case_type'], name='after_sales_order_i_8abae9_idx'),
        ),
        migrations.AddIndex(
            model_name='customermemory',
            index=models.Index(fields=['user', 'memory_type', 'is_active'], name='after_sales_user_id_233562_idx'),
        ),
        migrations.AddConstraint(
            model_name='customermemory',
            constraint=models.UniqueConstraint(fields=('user', 'memory_type', 'key'), name='after_sales_unique_customer_memory'),
        ),
        migrations.AddIndex(
            model_name='toolexecution',
            index=models.Index(fields=['conversation', 'created_at'], name='after_sales_convers_8c898d_idx'),
        ),
        migrations.AddIndex(
            model_name='toolexecution',
            index=models.Index(fields=['user', 'status'], name='after_sales_user_id_c70781_idx'),
        ),
        migrations.AddIndex(
            model_name='toolexecution',
            index=models.Index(fields=['tool_name', 'status'], name='after_sales_tool_na_786f03_idx'),
        ),
    ]
