# Generated by Django 5.1.4 on 2026-08-28 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('after_sales', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='toolexecution',
            name='agent_role',
            field=models.CharField(default='coordinator', max_length=32, verbose_name='执行 Agent'),
        ),
    ]
