# Generated by Django 5.1.4 on 2026-08-31

import django.db.models.deletion
import uuid
from django.db import migrations, models
from pgvector.django import HnswIndex, VectorExtension, VectorField


class Migration(migrations.Migration):

    dependencies = [
        ("after_sales", "0002_toolexecution_agent_role"),
    ]

    operations = [
        VectorExtension(),
        migrations.CreateModel(
            name="KnowledgeDocument",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=160, verbose_name="标题")),
                ("slug", models.SlugField(max_length=100, unique=True, verbose_name="稳定标识")),
                ("category", models.CharField(max_length=64, verbose_name="分类")),
                ("source_label", models.CharField(max_length=160, verbose_name="引用名称")),
                ("content", models.TextField(verbose_name="知识内容")),
                ("is_published", models.BooleanField(default=True, verbose_name="允许 Agent 检索")),
            ],
            options={
                "verbose_name": "售后知识文档",
                "verbose_name_plural": "售后知识文档",
                "ordering": ("category", "title"),
            },
        ),
        migrations.CreateModel(
            name="KnowledgeChunk",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("sequence", models.PositiveSmallIntegerField(verbose_name="切片序号")),
                ("content", models.TextField(verbose_name="切片内容")),
                ("content_hash", models.CharField(max_length=64, verbose_name="内容哈希")),
                (
                    "embedding",
                    VectorField(
                        blank=True, dimensions=1536, null=True, verbose_name="向量"
                    ),
                ),
                (
                    "document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chunks",
                        to="after_sales.knowledgedocument",
                        verbose_name="所属文档",
                    ),
                ),
            ],
            options={
                "verbose_name": "售后知识切片",
                "verbose_name_plural": "售后知识切片",
                "ordering": ("document", "sequence"),
                "indexes": [
                    models.Index(fields=["document", "sequence"], name="after_sales_documen_6ba5ae_idx"),
                    HnswIndex(
                        ef_construction=64,
                        fields=["embedding"],
                        m=16,
                        name="as_knowledge_emb_hnsw",
                        opclasses=["vector_cosine_ops"],
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("document", "sequence"), name="after_sales_unique_knowledge_chunk"
                    )
                ],
            },
        ),
    ]
