# Generated by Django 5.1.4 on 2026-09-02 00:56

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('after_sales', '0003_knowledge_document_and_chunk'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AfterSalesNotification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event_type', models.CharField(choices=[('CASE_CREATED', '工单创建'), ('CASE_APPROVED', '审核通过'), ('CASE_REJECTED', '审核拒绝'), ('NEED_CUSTOMER_INFO', '要求补充资料')], max_length=32, verbose_name='事件类型')),
                ('title', models.CharField(max_length=160, verbose_name='标题')),
                ('message', models.TextField(verbose_name='通知内容')),
                ('action_url', models.CharField(default='/after-sales', max_length=200, verbose_name='跳转地址')),
                ('is_read', models.BooleanField(default=False, verbose_name='已读')),
                ('read_at', models.DateTimeField(blank=True, null=True, verbose_name='阅读时间')),
                ('email_status', models.CharField(choices=[('PENDING', '待发送'), ('SENT', '模拟已发送'), ('SKIPPED', '无邮箱已跳过'), ('FAILED', '发送失败')], default='PENDING', max_length=16, verbose_name='邮件状态')),
                ('email_sent_at', models.DateTimeField(blank=True, null=True, verbose_name='邮件模拟发送时间')),
                ('email_error', models.CharField(blank=True, max_length=255, verbose_name='邮件错误')),
                ('after_sales_case', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='after_sales.aftersalescase', verbose_name='售后工单')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='after_sales_notifications', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '售后站内通知',
                'verbose_name_plural': '售后站内通知',
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['user', 'is_read', 'created_at'], name='after_sales_user_id_78f1a5_idx'), models.Index(fields=['email_status', 'created_at'], name='after_sales_email_s_c78138_idx')],
                'constraints': [models.UniqueConstraint(fields=('after_sales_case', 'event_type'), name='after_sales_unique_case_notification_event')],
            },
        ),
    ]
