# Generated by Django 5.1.4 on 2026-09-03

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("after_sales", "0004_notification_center"),
    ]

    operations = [
        migrations.CreateModel(
            name="AgentRun",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("model_name", models.CharField(blank=True, max_length=120, verbose_name="模型")),
                ("current_intent", models.CharField(blank=True, max_length=64, verbose_name="识别意图")),
                ("input_message", models.TextField(blank=True, verbose_name="用户输入")),
                ("assistant_message", models.TextField(blank=True, verbose_name="助手回复")),
                ("agent_roles", models.JSONField(blank=True, default=list, verbose_name="协作角色")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("RUNNING", "执行中"),
                            ("SUCCEEDED", "已完成"),
                            ("AWAITING_CONFIRMATION", "等待确认"),
                            ("ESCALATED", "已转人工"),
                            ("BLOCKED", "已拦截"),
                            ("FAILED", "失败"),
                        ],
                        default="RUNNING",
                        max_length=32,
                        verbose_name="运行状态",
                    ),
                ),
                ("failure_code", models.CharField(blank=True, max_length=100, verbose_name="失败代码")),
                ("failure_message", models.CharField(blank=True, max_length=255, verbose_name="失败说明")),
                ("response_id", models.CharField(blank=True, max_length=120, verbose_name="模型响应 ID")),
                ("tool_rounds", models.PositiveSmallIntegerField(default=0, verbose_name="工具轮数")),
                ("tool_call_count", models.PositiveSmallIntegerField(default=0, verbose_name="工具调用次数")),
                ("successful_tool_count", models.PositiveSmallIntegerField(default=0, verbose_name="成功工具数")),
                ("failed_tool_count", models.PositiveSmallIntegerField(default=0, verbose_name="失败工具数")),
                ("denied_tool_count", models.PositiveSmallIntegerField(default=0, verbose_name="拒绝工具数")),
                ("input_tokens", models.PositiveIntegerField(blank=True, null=True, verbose_name="输入 Token")),
                ("output_tokens", models.PositiveIntegerField(blank=True, null=True, verbose_name="输出 Token")),
                ("total_tokens", models.PositiveIntegerField(blank=True, null=True, verbose_name="总 Token")),
                ("started_at", models.DateTimeField(verbose_name="开始时间")),
                ("finished_at", models.DateTimeField(blank=True, null=True, verbose_name="结束时间")),
                ("duration_ms", models.PositiveIntegerField(blank=True, null=True, verbose_name="总耗时（毫秒）")),
                (
                    "confirmation_request",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="agent_runs",
                        to="after_sales.confirmationrequest",
                        verbose_name="确认请求",
                    ),
                ),
                (
                    "conversation",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="agent_runs",
                        to="after_sales.agentconversation",
                        verbose_name="会话",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="agent_runs",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="用户",
                    ),
                ),
            ],
            options={
                "verbose_name": "Agent 运行记录",
                "verbose_name_plural": "Agent 运行记录",
                "ordering": ("-started_at",),
                "indexes": [
                    models.Index(fields=["status", "started_at"], name="after_sales_status_8c2d6d_idx"),
                    models.Index(fields=["user", "started_at"], name="after_sales_user_id_913a4b_idx"),
                    models.Index(fields=["current_intent", "started_at"], name="after_sales_current_58a0b5_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="AgentRunEvent",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("MODEL_REQUEST", "模型请求"),
                            ("TOOL_EXECUTION", "工具执行"),
                            ("RUN_COMPLETED", "运行结束"),
                        ],
                        max_length=32,
                        verbose_name="事件类型",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("SUCCEEDED", "成功"),
                            ("FAILED", "失败"),
                            ("DENIED", "已拒绝"),
                            ("INFO", "信息"),
                        ],
                        max_length=16,
                        verbose_name="事件状态",
                    ),
                ),
                ("sequence", models.PositiveSmallIntegerField(verbose_name="顺序")),
                ("name", models.CharField(max_length=120, verbose_name="事件名称")),
                ("detail", models.JSONField(blank=True, default=dict, verbose_name="事件详情")),
                ("duration_ms", models.PositiveIntegerField(blank=True, null=True, verbose_name="耗时（毫秒）")),
                (
                    "run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="events",
                        to="after_sales.agentrun",
                        verbose_name="Agent 运行记录",
                    ),
                ),
            ],
            options={
                "verbose_name": "Agent 运行事件",
                "verbose_name_plural": "Agent 运行事件",
                "ordering": ("sequence", "created_at"),
                "indexes": [
                    models.Index(fields=["run", "sequence"], name="after_sales_run_id_2d4a7d_idx"),
                    models.Index(fields=["event_type", "created_at"], name="after_sales_event_t_1e0f8b_idx"),
                ],
            },
        ),
        migrations.AddField(
            model_name="toolexecution",
            name="run",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="tool_executions",
                to="after_sales.agentrun",
                verbose_name="Agent 运行记录",
            ),
        ),
    ]
