# Generated by Django 5.1.4 on 2026-09-03 02:33

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('after_sales', '0005_agent_observability'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='agentrun',
            new_name='after_sales_status_cfd4d0_idx',
            old_name='after_sales_status_8c2d6d_idx',
        ),
        migrations.RenameIndex(
            model_name='agentrun',
            new_name='after_sales_user_id_1667a7_idx',
            old_name='after_sales_user_id_913a4b_idx',
        ),
        migrations.RenameIndex(
            model_name='agentrun',
            new_name='after_sales_current_293409_idx',
            old_name='after_sales_current_58a0b5_idx',
        ),
        migrations.RenameIndex(
            model_name='agentrunevent',
            new_name='after_sales_run_id_99f22c_idx',
            old_name='after_sales_run_id_2d4a7d_idx',
        ),
        migrations.RenameIndex(
            model_name='agentrunevent',
            new_name='after_sales_event_t_4c851c_idx',
            old_name='after_sales_event_t_1e0f8b_idx',
        ),
        migrations.AlterField(
            model_name='agentrun',
            name='started_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='开始时间'),
        ),
    ]
