# Generated by Django 5.1.4 on 2026-09-03 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('after_sales', '0006_rename_after_sales_status_8c2d6d_idx_after_sales_status_cfd4d0_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agentrunevent',
            name='event_type',
            field=models.CharField(choices=[('MODEL_REQUEST', '模型请求'), ('TOOL_EXECUTION', '工具执行'), ('HUMAN_ACTION', '人工操作'), ('RUN_COMPLETED', '运行结束')], max_length=32, verbose_name='事件类型'),
        ),
    ]
