# Generated by Django 5.1.4 on 2026-09-03 10:28

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('after_sales', '0007_alter_agentrunevent_event_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentEvaluationRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('RUNNING', '执行中'), ('SUCCEEDED', '已完成'), ('FAILED', '失败')], default='RUNNING', max_length=16, verbose_name='评测状态')),
                ('trigger', models.CharField(choices=[('DASHBOARD', '后台工作台'), ('COMMAND', '管理命令')], default='DASHBOARD', max_length=16, verbose_name='触发方式')),
                ('mode', models.CharField(default='deterministic_replay', max_length=64, verbose_name='评测模式')),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='开始时间')),
                ('finished_at', models.DateTimeField(blank=True, null=True, verbose_name='结束时间')),
                ('total_cases', models.PositiveIntegerField(default=0, verbose_name='案例总数')),
                ('passed_cases', models.PositiveIntegerField(default=0, verbose_name='通过案例数')),
                ('failed_cases', models.PositiveIntegerField(default=0, verbose_name='失败案例数')),
                ('intent_correct', models.PositiveIntegerField(default=0, verbose_name='意图正确数')),
                ('intent_total', models.PositiveIntegerField(default=0, verbose_name='意图评测数')),
                ('tool_selection_correct', models.PositiveIntegerField(default=0, verbose_name='工具选择正确数')),
                ('tool_selection_total', models.PositiveIntegerField(default=0, verbose_name='工具选择评测数')),
                ('parameter_correct', models.PositiveIntegerField(default=0, verbose_name='参数正确数')),
                ('parameter_total', models.PositiveIntegerField(default=0, verbose_name='参数评测数')),
                ('unauthorized_blocked', models.PositiveIntegerField(default=0, verbose_name='越权拦截数')),
                ('unauthorized_total', models.PositiveIntegerField(default=0, verbose_name='越权案例数')),
                ('dangerous_blocked', models.PositiveIntegerField(default=0, verbose_name='危险操作拦截数')),
                ('dangerous_total', models.PositiveIntegerField(default=0, verbose_name='危险操作案例数')),
                ('human_escalated', models.PositiveIntegerField(default=0, verbose_name='人工转接数')),
                ('human_escalation_total', models.PositiveIntegerField(default=0, verbose_name='人工转接评测数')),
                ('failure_total', models.PositiveIntegerField(default=0, verbose_name='运行失败数')),
                ('average_response_ms', models.PositiveIntegerField(default=0, verbose_name='平均响应时间（毫秒）')),
                ('report', models.JSONField(blank=True, default=dict, verbose_name='完整评测报告')),
                ('error_message', models.CharField(blank=True, max_length=255, verbose_name='错误说明')),
            ],
            options={
                'verbose_name': 'Agent 评测批次',
                'verbose_name_plural': 'Agent 评测批次',
                'ordering': ('-started_at',),
                'indexes': [models.Index(fields=['status', 'started_at'], name='after_sales_status_6e9f53_idx'), models.Index(fields=['trigger', 'started_at'], name='after_sales_trigger_7685ce_idx')],
            },
        ),
        migrations.CreateModel(
            name='AgentEvaluationCaseResult',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('case_id', models.CharField(max_length=32, verbose_name='案例 ID')),
                ('category', models.CharField(max_length=64, verbose_name='案例类别')),
                ('description', models.CharField(max_length=255, verbose_name='案例说明')),
                ('message', models.TextField(verbose_name='测试输入')),
                ('expected_intent', models.CharField(max_length=64, verbose_name='期望意图')),
                ('actual_intent', models.CharField(blank=True, max_length=64, verbose_name='实际意图')),
                ('expected_tools', models.JSONField(blank=True, default=list, verbose_name='期望工具')),
                ('actual_tools', models.JSONField(blank=True, default=list, verbose_name='实际工具')),
                ('expected_arguments', models.JSONField(blank=True, default=list, verbose_name='期望参数')),
                ('actual_arguments', models.JSONField(blank=True, default=list, verbose_name='实际参数')),
                ('passed', models.BooleanField(default=False, verbose_name='案例通过')),
                ('intent_passed', models.BooleanField(default=False, verbose_name='意图正确')),
                ('tool_selection_passed', models.BooleanField(default=False, verbose_name='工具选择正确')),
                ('parameter_applicable', models.BooleanField(default=False, verbose_name='参数可评测')),
                ('parameter_passed', models.BooleanField(blank=True, null=True, verbose_name='参数正确')),
                ('authorization_passed', models.BooleanField(default=False, verbose_name='权限断言通过')),
                ('unauthorized_case', models.BooleanField(default=False, verbose_name='越权案例')),
                ('unauthorized_blocked', models.BooleanField(default=False, verbose_name='越权已拦截')),
                ('dangerous_case', models.BooleanField(default=False, verbose_name='危险操作案例')),
                ('dangerous_blocked', models.BooleanField(default=False, verbose_name='危险操作已拦截')),
                ('response_compliance_passed', models.BooleanField(default=False, verbose_name='回复合规')),
                ('human_escalated', models.BooleanField(default=False, verbose_name='已转人工')),
                ('failed', models.BooleanField(default=False, verbose_name='运行失败')),
                ('response_time_ms', models.PositiveIntegerField(default=0, verbose_name='响应时间（毫秒）')),
                ('actual_error_codes', models.JSONField(blank=True, default=list, verbose_name='实际错误代码')),
                ('assistant_message', models.TextField(blank=True, verbose_name='助手回复')),
                ('failures', models.JSONField(blank=True, default=list, verbose_name='失败说明')),
                ('evaluation_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='case_results', to='after_sales.agentevaluationrun', verbose_name='评测批次')),
            ],
            options={
                'verbose_name': 'Agent 评测案例结果',
                'verbose_name_plural': 'Agent 评测案例结果',
                'ordering': ('case_id',),
                'indexes': [models.Index(fields=['evaluation_run', 'passed'], name='after_sales_evaluat_f8919a_idx'), models.Index(fields=['category', 'case_id'], name='after_sales_categor_c23763_idx')],
                'constraints': [models.UniqueConstraint(fields=('evaluation_run', 'case_id'), name='after_sales_unique_eval_run_case')],
            },
        ),
    ]
