# Generated by Django 5.1.4 on 2026-09-05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("after_sales", "0008_agentevaluationrun_agentevaluationcaseresult"),
        ("products", "0002_alter_category_options_alter_product_options_and_more"),
        ("authentication", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="knowledgedocument",
            name="chunk_count",
            field=models.PositiveIntegerField(default=0, verbose_name="切片数量"),
        ),
        migrations.AddField(
            model_name="knowledgedocument",
            name="file",
            field=models.FileField(blank=True, null=True, upload_to="after-sales/knowledge/", verbose_name="原始文件"),
        ),
        migrations.AddField(
            model_name="knowledgedocument",
            name="index_error",
            field=models.CharField(blank=True, max_length=500, verbose_name="索引错误"),
        ),
        migrations.AddField(
            model_name="knowledgedocument",
            name="index_status",
            field=models.CharField(
                choices=[
                    ("PENDING", "待索引"),
                    ("PROCESSING", "索引中"),
                    ("READY", "已就绪"),
                    ("FAILED", "索引失败"),
                ],
                default="PENDING",
                max_length=16,
                verbose_name="索引状态",
            ),
        ),
        migrations.AddField(
            model_name="knowledgedocument",
            name="indexed_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="索引完成时间"),
        ),
        migrations.AddField(
            model_name="knowledgedocument",
            name="product_category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="after_sales_knowledge_documents",
                to="products.category",
                verbose_name="适用商品分类",
            ),
        ),
        migrations.AddField(
            model_name="knowledgedocument",
            name="product",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="after_sales_knowledge_documents",
                to="products.product",
                verbose_name="适用商品",
            ),
        ),
        migrations.AddField(
            model_name="knowledgedocument",
            name="source_type",
            field=models.CharField(
                choices=[("TEXT", "文本"), ("FILE", "文件"), ("WEBPAGE", "网页")],
                default="TEXT",
                max_length=16,
                verbose_name="来源类型",
            ),
        ),
        migrations.AddField(
            model_name="knowledgedocument",
            name="source_url",
            field=models.URLField(blank=True, max_length=1000, verbose_name="网页地址"),
        ),
        migrations.AddField(
            model_name="knowledgedocument",
            name="uploaded_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="uploaded_knowledge_documents",
                to="authentication.user",
                verbose_name="上传人",
            ),
        ),
        migrations.AddField(
            model_name="knowledgechunk",
            name="vector_id",
            field=models.CharField(blank=True, max_length=100, verbose_name="向量库 ID"),
        ),
        migrations.AddIndex(
            model_name="knowledgedocument",
            index=models.Index(fields=["index_status", "updated_at"], name="after_sales_kdoc_idx"),
        ),
        migrations.AddIndex(
            model_name="knowledgedocument",
            index=models.Index(fields=["product", "is_published"], name="after_sales_kprod_idx"),
        ),
        migrations.AddIndex(
            model_name="knowledgedocument",
            index=models.Index(fields=["product_category", "is_published"], name="after_sales_kcat_idx"),
        ),
        migrations.RunPython(
            code=lambda apps, schema_editor: apps.get_model("after_sales", "KnowledgeDocument")
            .objects.filter(chunks__isnull=False)
            .update(index_status="READY"),
            reverse_code=migrations.RunPython.noop,
        ),
    ]
