# Generated by Django 5.1.4 on 2026-09-05 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('after_sales', '0009_knowledge_document_management'),
    ]

    operations = [
        migrations.AlterField(
            model_name='knowledgedocument',
            name='index_status',
            field=models.CharField(choices=[('PENDING', '待索引'), ('PROCESSING', '索引中'), ('READY', '已就绪'), ('DEGRADED', '已降级（PostgreSQL）'), ('FAILED', '索引失败')], default='PENDING', max_length=16, verbose_name='索引状态'),
        ),
    ]
